name: Publish Package

on:
  push:
    branches:
      - master

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm i pnpm -g
      - run: pnpm i
      - run: pnpm run build
      - run: pnpm publish -access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
